#!/bin/bash

sed -i -e "s#\"HUD_PARAM_TEST_HOST_ARRAY\"#$HUD_PARAM_TEST_HOST_ARRAY#" \
    -e "s#\"HUD_PARAM_STORAGE_SERVER\"#$HUD_PARAM_STORAGE_SERVER#" \
    -e "s#\"HUD_PARAM_DISK_MAPPER_SERVER_ACTIVE\"#$HUD_PARAM_DISK_MAPPER_SERVER_ACTIVE#" \
    -e "s#\"HUD_PARAM_DISK_MAPPER_SERVER_PASSIVE\"#$HUD_PARAM_DISK_MAPPER_SERVER_PASSIVE#" \
    -e "s#\"HUD_PARAM_ACTIVE_DM_KEY\"#$HUD_PARAM_ACTIVE_DM_KEY#" \
    -e "s#\"HUD_PARAM_MEMBASE_BUILD\"#$HUD_PARAM_MEMBASE_BUILD#" \
    -e "s#\"HUD_PARAM_PROXYSERVER_BUILD\"#$HUD_PARAM_PROXYSERVER_BUILD#" \
    -e "s#\"HUD_PARAM_BACKUP_TOOL_BUILD\"#$HUD_PARAM_BACKUP_TOOL_BUILD#" \
    -e "s#\"HUD_PARAM_PECL_BUILD\"#$HUD_PARAM_PECL_BUILD#" \
    -e "s#\"HUD_PARAM_DISK_MAPPER_BUILD\"#$HUD_PARAM_DISK_MAPPER_BUILD#" \
    -e "s#\"HUD_PARAM_STORAGE_SERVER_BUILD\"#$HUD_PARAM_STORAGE_SERVER_BUILD#" \
    -e "s#\"/tmp/results\"#'/tmp/$JOB_NAME'#" \
    -e "s#\"HUD_PARAM_TEST_SUITE_ARRAY\"#$HUD_PARAM_TEST_SUITE_ARRAY#" config.php