#Constants for IPMAPPER

VBS_PORT=14000

IPMAPPER_PORT=12000
IPMAPPER_LOG_FILE='/var/log/IPM.log'
IPMAPPER_MAP_FILE='/var/tmp/IPMapper/IPM.map'

VBA_START_IP=4
MOXI_START_IP=100
MOXI_START_PORT=13500
